version: '3.11.4'
services:
  bootcamp:
    image: jannatun/dash:v0.1
    container_name: carprice
    build:
      context: .
      dockerfile: dash.Dockerfile
    volumes:
      - ./code:/root/code
      - ./data:/root/data
      - ./model:/root/model
      - ./scale:/root/scale
      - ./.vscode-server:/root/.vscode-server
mlflow:
    image: mlflow:latest
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: mlflow.Dockerfile
    volumes:
      - ./_mlflow:/mlflow
    ports:
      - 5000:5000 
       