version: '3.9'
services:
  bootcamp:
    image: jannatun/dash:v0.1
    container_name: carprice
    build:
      context: .
      dockerfile: dash.Dockerfile
    volumes:
      - ./.vscode-server:/root/.vscode-server
      - ./code:/root/code

    ports:
    - 9999:8050